spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://epuz.crqrcxnf62hg.ap-northeast-2.rds.amazonaws.com:3306/epuz
    username: username1
    password: password1
    
mybatis:
  mapper-locations:
  - classpath*:mappers/*xml
  type-aliases-package: com/epuz/web/dto
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30